services:
  - type: web
    name: techstore
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: 8f42a73054b1749f8f58848be5e6502c8f42a73054b1749f8f58848be5e6502c
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: techstore-db
          property: connectionString

  - type: redis
    name: techstore-db
    plan: free
    ipAllowList: []

databases:
  - name: ecommerce-db
    databaseName: ecommerce
    user: ecommerce_user
    plan: free 