"""Add is_authenticated to Visitor model

Revision ID: b05147dd2e40
Revises: a951e2cb9916
Create Date: 2024-03-21 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05147dd2e40'
down_revision = 'a951e2cb9916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('ip',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=50),
               existing_nullable=True,
               nullable=False)
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_visitor_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_constraint('fk_visitor_user_id', type_='foreignkey')
        batch_op.alter_column('user_agent',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('ip',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=45),
               existing_nullable=False,
               nullable=True)
        batch_op.drop_column('user_id')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
